[package]
name = "aptos-tx-filter"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wee_alloc = "0.4"
log = "0.4"
lazy_static = "1.4"

[dependencies.wasi]
version = "0.10.2+wasi-snapshot-preview1"

[lib]
name = "aptos_filter_rs"
path = "aptos.rs"
crate-type = ["cdylib"]